# Generated by Django 4.0 on 2021-12-08 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
